Repository skycoin/skycoin, pull requests merged in 2018-03, with the labels that each got.

#991 [lib] [test] refs #906 - Continuous integration steps for libskycoin C API
  .gitignore
  .travis.yml
  Makefile
  README.md
  include/libskycoin.h
Labels: stdev, wip

#1036 [util] [cmd] fixes #966 closes #1002 - Expand -data-dir relative to $PWD . OS env vars not supported
  cmd/skycoin/skycoin.go
  src/util/file/file.go
  src/util/file/file_test.go
Labels: stdev, wip

#1002 [util] fixes #966 closes #1036 - Expand data-dir paths relative to working directory
  cmd/skycoin/skycoin.go
  src/util/file/file.go
  src/util/file/file_test.go
Labels: stdev, wip

#1037 [lib] fixes #1028 - README file for libskycoin
  README.md
  lib/cgo/README.md
Labels: stdev, wip

#1061 Add CLI send integration test
  src/api/cli/integration/integration_test.go
Labels: cli, tests

#1088 [lib] fixes #1027 - Temporary patch to deal with frequent modification of include/libskycoin.h
  .gitignore
  include/libskycoin.h
Labels: stdev, wip

#1136 Add GUI injectTransaction integration test
  ci-scripts/integration-test-live.sh
  src/api/cli/integration/integration_test.go
  src/gui/client.go
  src/gui/integration/integration_test.go
Labels: api, tests

#1166 [util] fixes #1161 - logging compatibility
  src/util/logging/formatter.go
  src/util/logging/hooks.go
  src/util/logging/logger.go
  src/util/logging/logging.go
Labels: stdev, wip
