Repository skycoin/skycoin, pull requests merged in 2018-05, with the labels that each got.

#1341 Cli with encryption
  CHANGELOG.md
  src/api/cli/add_private_key.go
  src/api/cli/check_balance.go
  src/api/cli/cli.go
  src/api/cli/create_rawtx.go
  src/api/cli/decryptWallet.go
  src/api/cli/encrypt_wallet.go
  src/api/cli/generate_addrs.go
  src/api/cli/generate_wallet.go
  src/api/cli/integration/integration_test.go
  src/api/cli/integration/test-fixtures/generate-addresses-encrypted.golden
  src/api/cli/integration/test-fixtures/integration-test-encrypted.wlt
  src/api/cli/list_addrs.go
  src/api/cli/list_wallets.go
  src/api/cli/send.go
  src/api/cli/show_seed.go
  src/wallet/service.go
  src/wallet/service_test.go
  src/wallet/wallet.go
  src/wallet/wallet_test.go
Labels: cli

#1439 [cipher] fixes #1437 - Support in cipher/encoder for decoding map values
  CHANGELOG.md
  src/cipher/encoder/encoder.go
  src/cipher/encoder/encoder_test.go
Labels: stdev, wip

#1389 [cli] Fixes #1315 Created a DATA_DIR env var in CLI
  CHANGELOG.md
  src/api/cli/cli.go
  src/api/cli/cli_test.go
Labels: stdev, wip

#1465 [ci] fixes #1457 - Travis builds for (public) forks
  .travis.yml
Labels: stdev, wip

#1492 Set time value in /transaction api response & clean up unused disable wallet api settings for CLI integration test
  ci-scripts/integration-test-disable-wallet-api.sh
  src/api/transaction.go
  src/cli/integration/integration_test.go
Labels: api

#1455 [gui] fixes #1388 Add PeerHeight field in /network/connection(s) endpoints
  CHANGELOG.md
  src/api/README.md
  src/api/client.go
  src/api/gatewayer_mock_test.go
  src/api/integration/integration_test.go
  src/api/network.go
  src/api/network_test.go
Labels: stdev, wip

#1431 [docker] fixes #1190 Adds docker builds for ARM arch
  .gitignore
  .travis.yml
  README.md
  docker/images/mainnet/Dockerfile
  docker/images/mainnet/README.md
  docker/images/mainnet/hooks/build
  docker/images/mainnet/hooks/push
Labels: docker, stdev, wip

#1241 [test] [util] fixes #1110 fixes #913 - Annotated hexdump
  src/daemon/messages_test.go
  src/util/hexdump.go
Labels: stdev, wip
