Repository skycoin/skycoin, pull requests merged in 2018-12, with the labels that each got.

#1997 fixes #1896 - Metadata files for the skycoindev-cli:dind image
  README.md
  docker/images/dev-cli/Dockerfile
  docker/images/dev-cli/README.md
  docker/images/dev-cli/hooks/build
  docker/images/dev-docker/Dockerfile
  docker/images/dev-docker/README.md
  docker/images/dev-docker/hooks/build
  docker/images/mainnet/Dockerfile
  docker/images/mainnet/hooks/build
Labels: docker, stdev, wip

#2030 Fixes #2029 Errors retrieving repository GPG keys lead to Docker build failure (Debian)
  docker/images/dev-cli/Dockerfile
Labels: stdev, wip

#2010 [docker] Skycoin-dev image with GUI VSCode IDE - fixes #1434
  README.md
  docker/images/dev-cli/README.md
  docker/images/dev-vscode/Dockerfile
  docker/images/dev-vscode/README.md
  docker/images/dev-vscode/hooks/build
  docker/images/dev-vscode/hooks/push
  docker/images/dev-vscode/start.sh
Labels: docker, stdev, wip

#1641 [lib] fixes #1568 - Add swig files for creating libraries in other languages, tested with python.
  CHANGELOG.md
  include/skytypes.h
  include/swig.h
  lib/cgo/coin.math.go
  lib/swig/common/cmp.i
  lib/swig/common/common.i
  lib/swig/common/mem.i
  lib/swig/common/typemaps.i
  lib/swig/dynamic/dynamic.i
  lib/swig/dynamic/golang.cgo.i
  lib/swig/dynamic/mem.i
  lib/swig/dynamic/typemaps.i
  lib/swig/static/skycoin.cipher.crypto.i
  lib/swig/static/skycoin.coin.i
  lib/swig/static/static.i
Labels: libc, stdev, wip

#2037 [lib] fixes #2036 - lib/swig/README.md version 1
  README.md
  lib/swig/README.md
Labels: stdev, wip

#2044 [release] fixes #2041 fixes #2047 - Release 0.25.0 - step 6 - Merge into develop
  .travis.yml
  Makefile
  README.md
  cmd/cli/README.md
  fiber.toml
  src/api/README.md
  src/util/useragent/useragent_test.go
Labels: stdev, wip

#2053 [skycoin] fixes #2052 - Accept all valid API set names
  src/skycoin/config.go
Labels: stdev, wip

#2056 [docker] fixes #2055 - Fix failures building Docker in Docker image
  docker/images/dev-docker/hooks/build
Labels: stdev, wip

#2062 refs #2061 - Fix typo in README release steps list
  README.md
Labels: stdev, wip
