Repository skycoin/skycoin, pull requests merged in 2018-06, with the labels that each got.

#1183 [docker] [skycoindev] fixes #1073 fixes #1481 - Adds Dockerfile to build dev image.
  CHANGELOG.md
  README.md
  docker/images/dev-cli/Dockerfile
  docker/images/dev-cli/README.md
Labels: docker, stdev, wip

#1225 [lib] fixes #992 fixes #1182 fixes #1537 - libskycoin v0.24.0-alpha
  .Doxyfile
  .gitignore
  .travis.yml
  CHANGELOG.md
  Makefile
  README.md
  docs/assets/sky.libc.jpg
  docs/libc/API.md
  include/base64.h
  include/cipher.address.go.h
  include/cipher.crypto.go.h
  include/cipher.hash.go.h
  include/cipher.testsuite.testsuite.go.h
  include/cli.create_rawtx.go.h
  include/coin.outputs.go.h
  include/coin.transactions.go.h
  include/json.h
  include/skycriterion.h
  include/skyerrors.h
  include/skystring.h
  include/skytest.h
  include/skytypes.h
  include/wallet.entry.go.h
  include/wallet.wallet.go.h
  lib/cgo/README.md
  lib/cgo/api.webrpc.client.go
  lib/cgo/cipher.address.go
  lib/cgo/cipher.crypto.go
  lib/cgo/cipher.hash.go
  lib/cgo/cli.create_rawtx.go
  lib/cgo/coin.outputs.go
  lib/cgo/libsky_error.go
  lib/cgo/libsky_handle.go
  lib/cgo/libsky_mem.go
  lib/cgo/main.go
  lib/cgo/tests/check_cipher.address.c
  lib/cgo/tests/check_cipher.c
  lib/cgo/tests/check_cipher.crypto.c
  lib/cgo/tests/check_cipher.hash.c
  lib/cgo/tests/check_cipher.testsuite.c
  lib/cgo/tests/cipher.testsuite.c
  lib/cgo/tests/libsky_criterion.c
  lib/cgo/tests/libsky_string.c
  lib/cgo/tests/libsky_testutil.c
  lib/cgo/tests/testutils/base64.c
  lib/cgo/tests/testutils/json.c
  lib/cgo/tests/testutils/json_util.c
  lib/cgo/wallet.wallet.go
  lib/cgo/wallet_option.go
Labels: stdev, wip

#1612 [cipher] [daemon] fixes #1609 - hexdump empty slice
  src/cipher/encoder/encoder.go
  src/daemon/messages_test.go
Labels: core, stdev, wip

#1630 fixes #1538 - Skycoin images base image = busybox
  CHANGELOG.md
  docker/images/mainnet/Dockerfile
  docker/images/mainnet/hooks/build
Labels: stdev, wip

#1652 [docker] fixes #1645 - Fix Docker build errors in skycoin/skycoin image due to lib/cgo
  docker/images/mainnet/Dockerfile
Labels: docker, stdev, wip

#1651 [lib] [ci] fixes #1632 - Successful travis builds on macos slaves
  .travis.yml
  lib/cgo/tests/check_cipher.crypto.c
  lib/cgo/tests/cipher.testsuite.c
  lib/cgo/tests/libsky_criterion.c
  lib/cgo/tests/testutils/json_util.c
Labels: libc, stdev, tests, wip

#1646 [daemon] [encoder] fixes #1603 - Add support for omitempty tag to messages hexdumps generator
  src/cipher/encoder/encoder.go
  src/daemon/messages_test.go
  src/util/hexdump.go
Labels: stdev, wip

#1656 [gui] Fixes #1654 - Remove owner parameter when unzipping dist files
  electron/compress-standalone-release.sh
Labels: stdev, wip

#1668 [docker] Fix #1667 Update version of SWIG to 3.0.12 in skycoin/skycoindev-cli docker image
  CHANGELOG.md
  docker/images/dev-cli/Dockerfile
Labels: stdev, wip

#1666 [ci] fixes #1661 - Separate make build-libc-static and build-libc-shared targets
  Makefile
Labels: stdev, wip

#1663 [docker] Fixes #1659 Create docker in docker image based on skycoindev-cli
  CHANGELOG.md
  docker/images/dev-docker/Dockerfile
  docker/images/dev-docker/README.md
  docker/images/dev-docker/dockerd-entrypoint.sh
  docker/images/dev-docker/modprobe.sh
Labels: docker, stdev, wip

#1672 Fix history db resetting bug
  src/visor/historydb/historydb.go
Labels: bug, core, fiber

#1676 Fix a bug in cipher-testdata generator and update the testdata
  cmd/cipher-testdata/cipher-testdata.go
  src/cipher/testsuite/testdata/input-hashes.golden
  src/cipher/testsuite/testdata/many-addresses.golden
  src/cipher/testsuite/testdata/seed-0000.golden
  src/cipher/testsuite/testdata/seed-0001.golden
  src/cipher/testsuite/testdata/seed-0002.golden
  src/cipher/testsuite/testdata/seed-0003.golden
  src/cipher/testsuite/testdata/seed-0004.golden
  src/cipher/testsuite/testdata/seed-0005.golden
  src/cipher/testsuite/testdata/seed-0006.golden
  src/cipher/testsuite/testdata/seed-0007.golden
  src/cipher/testsuite/testdata/seed-0008.golden
  src/cipher/testsuite/testdata/seed-0009.golden
  src/cipher/testsuite/testdata/seed-0010.golden
Labels: tests

#1595 Check blockchain pubkey in INTR message if extra bytes exist
  src/daemon/daemon.go
  src/daemon/daemoner_mock_test.go
  src/daemon/gateway.go
  src/daemon/gnet/dispatcher.go
  src/daemon/gnet/dispatcher_test.go
  src/daemon/messages.go
  src/daemon/messages_test.go
  src/skycoin/skycoin.go
Labels: docs, networking

#1674 [docker] fixes #1670 - Install less command inside skycoin/skycoindev-cli image.
  CHANGELOG.md
  docker/images/dev-cli/Dockerfile
Labels: docker, stdev, wip

#1685 [docker] fixes #1681 - Install dep 0.4.1 package in skycoindev-cli image
  docker/images/dev-cli/Dockerfile
  docker/images/dev-cli/README.md
Labels: docker, stdev, wip
