Repository skycoin/skycoin, pull requests merged in 2018-09, with the labels that each got.

#1841 [docker] fixes # 1840 - Add GolangCI-Lint package to docker image
  docker/images/dev-cli/Dockerfile
Labels: stdev, wip

#1845 [docker] fixes #1844 - Add gocovmerge package to the development docker image
  docker/images/dev-cli/Dockerfile
Labels: docker, stdev, wip

#1847 [daemon] refs #1839 - Use valid sigs in message tests
  src/daemon/messages_test.go
Labels: docs, stdev, wip

#1852 fixes #1851 - Correct installation of dep for development
  README.md
Labels: docs, stdev, wip

#1908 [docker] fixes #1903 Docker reduce number of layers in skycoin/skycoin image
  docker/images/mainnet/Dockerfile
Labels: stdev, wip
